### ISSUE TITLE
Example pointtopoint command?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [jonnyhuck/Viewshed#18]
Does this look correct?

./viewshed -r 20000 -pointtopointax 345677 -pointtopointay 456788 -pointtopointbx 345678 -pointtopointby 456789  -z 50 -o 1.5 -t 100 -i DEM.tif -f VIEWSHED.tif

**Comment by jonnyhuck** [comment]
I think that you will need two dashes before the long form flags:

./viewshed -r 20000 --pointtopointax 345677 --pointtopointay 456788 --pointtopointbx 345678 --pointtopointby 456789 -z 50 -o 1.5 -t 100 -i DEM.tif -f VIEWSHED.tif

**Comment by WorksWellWithOthers** [comment]
Would this be the correct values in the command?
I'm not sure what values to put other than decimal coordinates. 

Latitude: 27.986065
Longitude: 86.922623

./viewshed -r 20000 --pointtopointax 27986 --pointtopointay 86922 --pointtopointbx 27987 --pointtopointby 86923 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

**Comment by WorksWellWithOthers** [comment]
./viewshed -r 20000 --pointtopointax 345677 --pointtopointay 456788 --pointtopointbx 345678 --pointtopointby 456789 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

ERROR 5: data.tif, band 1: Access window out of range in RasterIO().  Requested
(-6600,10200) of size 800x800 on raster of 600x600.

**Comment by jonnyhuck** [comment]
It looks like the coordinates that you are using are not within the dataset, possibly because they are in a different coordinate reference system. Are you able to check the bounds of your dataset using QGIS, GDALinfo or similar?

**Comment by WorksWellWithOthers** [comment]
I'm sorry but I am not knowledgeable about any of this stuff. 
I'm doing my best following the README and the examples in it. 

Those points are from the README example. The data.tif is from the repo, there is no longer a DEM.tif in the repo. 
My assumption was that DEM.tif got renamed to data.tif.

I'll search through the history and see if DEM.tif was indeed renamed to data.tif.
I'll also check and see what coordinates any tests are using against data.tif and try again with those values.

**Comment by WorksWellWithOthers** [comment]
Ok, it looks like data.tif was added with the test data commit and there was no such thing as DEM.tif in the repo, it was an example of a file that can be passed in as an input.

**Comment by WorksWellWithOthers** [comment]
The make file uses 'data.tif'

./viewshed -r 10000 -x 325000 -y 515000 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

I'll try the values from that command.

**Comment by WorksWellWithOthers** [comment]
./viewshed -r 10000 -x 325000 -y 515000 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

works without errors but

./viewshed -r 20000 --pointtopointax 325000 --pointtopointay 515000 --pointtopointbx 325001 --pointtopointby 515001 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

Complains about the access window being out of range.
I'm not sure what values work with data.tif to check pointtopoint.

**Comment by jonnyhuck** [comment]
I think that the problem with the second example is the radius argument (-r 20000), which will be making it do a full viewshed with a radius of 20km, which will make it fall off the edge of the dataset. If you remove the -r 20000 then it should work I think

**Comment by WorksWellWithOthers** [comment]
Thank you for your patience. I am slowly learning.

**Comment by WorksWellWithOthers** [comment]
./viewshed --pointtopointax 325000 --pointtopointay 515000 --pointtopointbx 325001 --pointtopointby 515001 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

ERROR 5: data.tif, band 1: Access window out of range in RasterIO().  Requested
(-6400,10400) of size 400x400 on raster of 600x600.

./viewshed -r 20 --pointtopointax 325000 --pointtopointay 515000 --pointtopointbx 325001 --pointtopointby 515001 -z 50
-o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

ERROR 1: data.tif, band 1: The buffer into which the data should be read is null
ERROR 1: Attempt to create 0x0 dataset is illegal,sizes must be larger than zero.
ERROR 10: Pointer 'hDS' is NULL in 'GDALSetGeoTransform'.

ERROR 10: Pointer 'hDS' is NULL in 'GDALSetProjection'.

ERROR 10: Pointer 'hDS' is NULL in 'GDALGetRasterBand'.

ERROR 10: Pointer 'hBand' is NULL in 'GDALRasterIO'.

**Comment by jonnyhuck** [comment]
Sorry, I'm not at a computer at the moment so can't test, can you try:

./viewshed -p --pointtopointax 325000 --pointtopointay 515000 --pointtopointbx 325001 --pointtopointby 515001 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

I think that you need the -p flag to get point to point to work. Otherwise I might need to do some testing tomorrow to get to the bottom of it

**Comment by WorksWellWithOthers** [comment]
./viewshed --pointtopoint --pointtopointax 325000 --pointtopointay 515000 --pointtopointbx 325001 --pointtopointby 515001 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif

Segmentation fault

**Comment by jonnyhuck** [comment]
Ok- let me test it and I'll get back to you- is it line of sight that you need rather than viewshed?

**Comment by WorksWellWithOthers** [comment]
Great question Honestly, I think both will work.
I need to check if two geolocation points are unobstructed.

**Comment by WorksWellWithOthers** [comment]
`./viewshed -r 20000 -x 345678 -y 456789 -z 50 -o 1.5 -t 100 -i data.tif -f VIEWSHED.tif`
This command is no longer working for me. I remember it working before (unless I'm remembering incorrectly). I wonder if I broke something on my machine.

**Comment by jonnyhuck** [comment]
Hi - OK, I have been through and tested - the viewshed function was working fine but there was a bug in the point to point function. I have fixed this and  added two examples to the README using the included data: 

Generate a Viewshed:
`./viewshed -r 10000 -x 325000 -y 515000 -z 50 -o 1.5 -t 100 -i data.tif -f viewshed.tif`

Determine point-to-point visibility - returns 1 (true) or 0 (false)):
`./viewshed -p -j 325000 -k 515000 -l 326000 -m 516000 -o 1.5 -t 100 -i data.tif`

How is that?

**Comment by WorksWellWithOthers** [comment]
Works great. Thank you.

Does 1 mean, "Yes, there is a line of sight" or "Yes, there is an obstruction and no line of sight"?
I think it's the first, "True, there is no obstruction and a clear line of sight between the two points.

What are those values called 325000, and 515000? 
I'm only used to lat long as decimal degrees. I'm unsure what to convert it to before passing it to Viewshed.

**Comment by jonnyhuck** [comment]
Yes, 1 is visible, 0 invisible.

These are projected coordinates (eastings and northings, measured in metres on a flat surface), as opposed to geographical coordinates (longitude and latitude, measured in degrees on a spheroid).

You would need to use the same coordinate reference system as your digital terrain model - in the case of the example data (data.tif), this is the [British National Grid](https://epsg.io/27700) (as it is a UK-based example). Raster data tend to use projected, rather than geographical coordinate reference systems, because they are made up of square cells, which would not be compatible with the round surface of the earth. For this reason, you will probably find that the terrain data you want to use will already be using a projected coordinate reference system, and you can simply use the same one. You can check the the CRS of your dataset using any GIS, or the [gdalinfo](https://gdal.org/programs/gdalinfo.html) command line tool, which will likely have installed alongside the dependencies for this software.

If you wanted an interface to the software that took values in longitude and latitude, you could use a library like [proj](https://proj.org/) to transform them before submitting them to the function. Alternatively (if you only had a few to do), you could transform them in any GIS, or using the [cs2cs](https://proj.org/apps/cs2cs.html) command line tool (which is again from proj).

Does that make sense?

**Comment by WorksWellWithOthers** [comment]
Yes, thank you.
