### ISSUE TITLE
Some examples

### ISSUE THREAD

**Issue by am2222** [jonnyhuck/Viewshed#8]
Hello,
Can you please share some example of the methods which we can run this code,
I have added a wgs1984 dem as input but it creates a black screen, What unite radius and other parameters should be? should they be based on Spatial reference system?

**Comment by jonnyhuck** [comment]
You would normally want to use a projected dataset rather than WGS84, as WGS84 coordinates are in degrees and so not strictly compatible with the cartesian geometry that is used in this software. In general I would stick to a projection for raster data as it means that your pixels will be of consistent size across the dataset (not the case on a spherical or ellipsoidal surface) .

Once projected (so that your coordinates are in metres), your command would be something along the lines of 

`./viewshed -r 20000 -x 345678 -y 456789 -z 50 -o 1.5 -t 100 -i DEM.tif -f VIEWSHED.tif`

That would run a viewshed of 20km around the point 345678,456789 assuming a 1.5m tall person looking for a 100m tall object in the landscape. The input data (50m resolution) would be DEM.tif and the output file would be saved to VIEWSHED.tif

Do you see how it works? I think your problem is simply that you have not projected your data, which you should be able to do in any GIS. Where is your DEM data from?

**Comment by jonnyhuck** [comment]
I have added this example to the README file - I hope that helps!

**Comment by am2222** [comment]
@jonnyhuck thanks very much, what If I convert x,y in code from degree to utm?Does it will work with wgs?Or it needs more conversations?

**Comment by jonnyhuck** [comment]
Yes, if you convert the coordinates to UTM, project your DEM data to the same UTM zone and then update the proj4 string then it should work fine

**Comment by am2222** [comment]
No I mean if I just convert those coordinates into x,y in algorithm using a convert function and use a WGS raster does it work?

**Comment by jonnyhuck** [comment]
No, because the data and your inputs will be in different coordinate systems. You need to use the same projected coordinate system for everything.

It is very easy to re-project your raster data using QGIS, just open the raster, then select Raster>Warp (Reproject) like [this](https://docs.qgis.org/2.2/en/docs/user_manual/plugins/plugins_gdaltools.html).

**Comment by am2222** [comment]
@jonnyhuck  Hi, My main problem is with georeferencing, I don't want to georeference my raster from wgs to utm, So I have to adapt the algorithm with wgs projection, I have no idea if it is possible or not?

**Comment by jonnyhuck** [comment]
Not really - the whole thing is written using geometry that assumes that you are on a flat surface, whereas WGS84 assumes that you are woring on the surface of a sphere. In general, large scale raster analysis like this would be done on a projected dataset, as using a spherical or ellipsoidal coordinate reference system would mean that the cells in your raster are not all the same size (because the raster is warped around a sphere).

However, it is possible if you really want to do it. Set the proj4 string to WGS84 and [convert your resolution and radius figures to to decimal degrees](https://gis.stackexchange.com/questions/2951/algorithm-for-offsetting-a-latitude-longitude-by-some-amount-of-meters). This will give you a result, **BUT** it will be done using an [Equirectangular Projection](https://en.wikipedia.org/wiki/Equirectangular_projection) - which is basically just pretending that the degrees are flat, not spherical units. As such, there will be a necessary sacrifice in precision, though this might be acceptable depending upon where in the world your analysis is / how large your radius is / what the purpose is etc.

Does that make sense?

**Comment by am2222** [comment]
@jonnyhuck hi, well I have to check this method to see how is accuracy,So you mean just resolution and radius would meke it work with wgs? well, with a brief look at the code, I get that most of calculations are done with distances which we can make it work in wgs, The main problem is with selecting pixels using resolution and radius, isn't it?
I think there could be some methods to increase this conversations accuracy

**Comment by am2222** [comment]
For example what if we change metric formulas in algorithm from metric into their degree forms? for example for distance :http://www.edwilliams.org/avform.htm#Dist

**Comment by jonnyhuck** [comment]
Yes, just changing the inputs to degrees should work, the calculation will just proceed on an equirectangular projection. I would imagine that the errors would be acceptable for a viewshed (especially given the uncertainties involved in viewshed anyway).

As you say, changing the geometry formulae to their spherical equivalents would also require a spherical solution to convert coordinates to pixels, otherwise you would probably get a similar effect to the above.

**Comment by am2222** [comment]
@jonnyhuck well,thanks very much for your help.I'll check and share the results,thanks

**Comment by jonnyhuck** [comment]
Great - please do let me know how you get on, and feel free to submit pull requests to the repo if you improve / add to the code in the process!

**Comment by am2222** [comment]
@jonnyhuck I converted both resolution and R to degrees which results 0.00027 for 30m dem and 0.0009 for 100m radius but it gives` floating point exception` I am still working to find the cause of this error

**Comment by jonnyhuck** [comment]
Hmmmm, sounds like it's something like 0.00027 is being rounded to 0 somewhere. can you show me the stack trace?

**Comment by am2222** [comment]
@jonnyhuck  yes in fact all values are converted into int when we add them to options struct, I changed them into double but It seems it does not work and calculations face problem, I also tried to reproject centerx,centery and adfgeotransform[0] and adfgeotransform[3] to utm and entered resolution and radius in meters as it seems just these (center point and top left point) coordinates are in degrees but it offsetx and offsety returns wrong values. Do you have any suggestion to fix this problem?
